baseurl = "https://la-fanjo.github.io/"
title = "Fanjo"
theme = "hugo-theme-console"
languageCode = "eo"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "pri/"
  url = "pri/"

  [[params.navlinks]]
  name = "nun/"
  url = "nun/"

  [[params.navlinks]]
  name = "blogo/"
  url = "blogo/"

  [[params.navlinks]]
  name = "taglibro/"
  url = "taglibro/"
  
  [[params.navlinks]]
  name = "fotoj/"
  url = "fotoj/"
